version: "3"
services:
  daraja-db:
    build:
        context: ./Dockerfile
        dockerfile: .
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    user: root
    environment:
      SA_PASSWORD: "pass@word1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1451:1433"
    volumes:
          - './docker/volumes/sqlserver/data:/var/opt/mssql/data'
          - './docker/volumes/sqlserver/log:/var/opt/mssql/log'
          - './docker/volumes/sqlserver/backup:/var/opt/mssql/backup'
    networks:
      - MpesaDaraja-api-network

  #MpesaDaraja-api:
  #  restart: on-failure
  #  depends_on: 
  #  - daraja-db
  #  networks:
  #    - MpesaDaraja-api-network

networks:
  MpesaDaraja-api-network:
    driver: bridge
  